spring.application.name=SpringAppxJDBC
spring.datasource.url=jdbc:postgresql://localhost:5432/xphinx
spring.datasource.username=postgres
spring.datasource.password=Saurabh@123
spring.datasource.driver-class-name=org.postgresql.Driver
